#!/bin/sh
# Shell script for downloading all notes from CATE.

read -p "Enter the year when the current academic year started, e.g. '2011': " year
read -p "Enter the course code for your course, e.g. 'c2': " ccode
read -p "Enter your DoC username: " username
read -s -p "Enter your DoC password: " password
echo "Downloading notes from CATE...\n"

curl https://$username:$password@cate.doc.ic.ac.uk/timetable.cgi?keyt=$year:{1,3,5}:$ccode:$username -s | grep -e \
  "<td rowspan=\"[0-9]\" bgcolor=\"white\"><b><font color=\"blue\">[0-9]*</font>[a-zA-Z0-9- ]*</b><br>" -A2 | sed "s/--//g" | sed 's/^[ \t]*//' | awk NF > .clist

grep .clist -e "<td" | awk '{print $4 $5 $6 $7}' | sed 's/color=\"blue\">\([0-9]*\)<\/font>\([a-zA-Z^<]*\)/\1\2/' | sed 's/<\/b><br>//' > .flist

mkdir CATE-Notes 2> /dev/null

cat .flist | while read line; do
  mkdir CATE-Notes/$line 2> /dev/null
  code=`echo $line | cut -f1 -d'-'`
  echo "Downloading notes for $line..."
  notescode=`grep .clist -e $code -A1 | grep "<a" | sed "s/<a href=\"notes.cgi\?key=$year:\([0-9]*\):[0-9]*:$ccode:new:$username\">/\1/" | head -n1`
  count=`curl https://$username:$password@cate.doc.ic.ac.uk/notes.cgi?key=$year:$notescode:3:$ccode:new:$username -s \
  | grep -c -e "<td align=center bgcolor=\"white\">pdf</td>"`
  noteslist=`curl https://$username:$password@cate.doc.ic.ac.uk/notes.cgi?key=$year:$notescode:3:$ccode:new:$username -s | grep -e "<a href=\"showfile.cgi" \
  | sed "s/<td bgcolor=\"white\"><a href=\"showfile.cgi\?key=$year:3:\([0-9]*\):$ccode:NOTES:$username\"/\1/" | cut -f1 -d'>'`

  echo "$count items found!"

  for i in $noteslist
  do
    name=`curl https://$username:$password@cate.doc.ic.ac.uk/notes.cgi?key=$year:$notescode:3:$ccode:new:$username -s | grep -e "<a href=\"showfile.cgi?key=$year:3:$i" \
    | sed "s/<td bgcolor=\"white\"><a href=\"showfile.cgi?key=$year:3:\([0-9]*\):$ccode:NOTES:$username\"/\1/" | cut -f2 -d'>' | cut -f1 -d'<'`
    echo "Downloading $name..."
    curl https://$username:$password@cate.doc.ic.ac.uk/showfile.cgi?key=$year:3:$i:$ccode:NOTES:$username -s -o "CATE-Notes/$line/$name.pdf"
  done
done

rm .clist
rm .flist
